<?php

namespace AppBundle\Repository;

/**
 * CommentairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentairesRepository extends \Doctrine\ORM\EntityRepository
{
	public function removeCommentaire($id)
	{
		$rq = $this->createQueryBuilder('u');
        
        $rq->delete()
        ->where('u.id = :id')
        ->setParameter('id', $id)
        ->getQuery()->getResult();
        
	}

}
