<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{

	public function getArticles($limit = 1){

		$rq = $this->createQueryBuilder('a');
        
        $rq->orderBy('a.created', 'DESC')
		   ->setMaxResults($limit);

       return $rq->getQuery()->getResult();

	}

	public function getUserArticle($id)
    {
    	$rq = $this->createQueryBuilder('a');

    	$rq->where('a.id_post');
    }

}
