# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    access_denied_url: security/forbidden.html.twig
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        AppBundle\Entity\Users: bcrypt

        # 73edb425b73397df254cf94d87a84f54
    
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    
    providers:
        main:
            entity:
                class: AppBundle:Users
                # property: username    

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern: ^/login$
            anonymous: true

        main:
            pattern: ^/
            provider: main
            form_login:
                login_path: login
                check_path: login_check
            anonymous: true

            logout:
                path: /logout
                target: /

            # remember_me:
                # key: "%secret%"
                # lifetime: 2232000
        default:
            anonymous: ~

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY }
